#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-asciidoctorj-groovy-dsl
Version  : 1.0.0.alpha3
Release  : 1
URL      : https://github.com/asciidoctor/asciidoctorj-groovy-dsl/archive/1.0.0.Alpha3.tar.gz
Source0  : https://github.com/asciidoctor/asciidoctorj-groovy-dsl/archive/1.0.0.Alpha3.tar.gz
Source1  : https://repo.gradle.org/gradle/libs-releases/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.jar
Source2  : https://repo.gradle.org/gradle/libs-releases/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-asciidoctorj-groovy-dsl-data = %{version}-%{release}
Requires: mvn-asciidoctorj-groovy-dsl-license = %{version}-%{release}
BuildRequires : buildreq-mvn
BuildRequires : gradle

%description
= Asciidoctor Groovy DSL
Robert Panzer <https://github.com/robertpanzer[@bobbytank42]>
:version: 0.0.1-SNAPSHOT
:asciidoc-url: http://asciidoc.org
:asciidoctor-url: http://asciidoctor.org
:groovy-url: http://beta.groovy-lang.org/
:gradle-url: http://gradle.org/
:asciidoctorj: https://github.com/asciidoctor/asciidoctorj
:lordofthejars: https://github.com/lordofthejars
:asciidoctor-docs: http://asciidoctor.org/docs/
:project-name: asciidoctor-groovy-dsl

%package data
Summary: data components for the mvn-asciidoctorj-groovy-dsl package.
Group: Data

%description data
data components for the mvn-asciidoctorj-groovy-dsl package.


%package license
Summary: license components for the mvn-asciidoctorj-groovy-dsl package.
Group: Default

%description license
license components for the mvn-asciidoctorj-groovy-dsl package.


%prep
%setup -q -n asciidoctorj-groovy-dsl-1.0.0.Alpha3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-asciidoctorj-groovy-dsl
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-asciidoctorj-groovy-dsl/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.jar
/usr/share/java/.m2/repository/org/asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/asciidoctorj-groovy-dsl-1.0.0.Alpha3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-asciidoctorj-groovy-dsl/LICENSE.txt
